


<form method="post" action="../back-end/ad_portfolio.php">


	<fieldset>
		<legend> Nouvelle réalisation</legend>

		<p>
		<label for="title"> Nom du Projet</label>
		<input type="texte" id="title" name="title">
		</p>

		<p>
			<label for="description">Description du Projet</label>
			<input type="text" id="descritption" name="description">
		</p>

		<p>
			<label for="mailaddress"> Adresse du Projet</label>
			<input type="text" id="mailaddress" name="mailaddress">
		</p>

		<p>
			<label for="nickname_author"> Prénom de l'auteur </label>
			<input type="authorId" id="nickname_author" name="nickname_author">
		</p>

		<p>
			<label for="lastname_author"> Nom de l'auteur </label>
			<input type="text" id="lastname_author" name="lastname_author">
	
		</p>		
		

		<p> <button class="buttonsubmit" type="submit"> Envoyer </button></p>

	</fieldset>

</form>