


	<div class="page"> 

	<h1> A PROPOS </h1>

	<div class="apropos"> 
	<div>
		<img class="profilhome" src="../sources/images/profil.jpg" alt="" width="350" height="500"/>
	</div>


<p class="presentation">
	"Je m'appelle Vanessa Caraes, j'ai 28 ans.
	Après avoir travaillé 5 ans dans la finance en tant que conseiller clientèle, j'ai ressenti le besoin d'élargir mes horizons et d'ajouter un bagage technique à mon profil.
	Après avoir effectué une formation diplômante de développeur Web, je suis à la recherche de nouvelles opportunités professionnelles afin d'enrichir mes connaissances et relever de nouveaux défis.

	Si mon profil vous intéresse n'hésitez pas à prendre contact avec moi <strong> <a href="contact.php"> ici </a> </strong>"
</div>

</p>
