

<main>
<div class="conteneur" > 
	<div  class="first_block">
		<h2> Vanessa-Ekessy Caraes </h2>
		<div class="conteneurimage">
			<img class="img" src="../sources/images/fond1.jpg">
		</div>
		<h2>Developpeur Web Junior</h2>	
		<div id="competence">
	<div id="premierblock">
		<h2> Compétences </h2>
		<ul>
				<li>Html5/Css3</li>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>		
				<div id="circle_grey"></div>
				<li>JavaSCript/Jquery/Ajax/JSON</li>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>		
				<div id="circle_grey"></div>
				<li>PhP</li>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>		
				<div id="circle_grey"></div>
				<li>MySql</li>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>		
				<div id="circle_grey"></div>
				<li>Bootsrap/Wordpress</li>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>		
				<div id="circle_grey"></div>	
				<li>PHOTOSHOP/ILLUSTRATOR</li>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>		
				<div id="circle_grey"></div>
		</ul>		
			</div>

			<div id="secondblock">
					<h2 > Compétences </h2>
		<ul>
				<li>Html5/Css3</li>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle_grey"></div>
				<li>JavaSCript/Jquery/Ajax/JSON</li>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle_grey"></div>
				<li>PhP</li>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle_grey"></div>
				<div id="circle_grey"></div>
				<li>MySql</li>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle_grey"></div>
				<li>Bootsrap/Wordpress</li>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle_grey"></div>
				<li>PHOTOSHOP/ILLUSTRATOR</li>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle"></div>
				<div id="circle_grey"></div>
		</ul>				
			</div>

	</div>
	<div class="test ">	
		<h2>Langues</h2>
			<ul class="non_list">
				<li><strong> Français :</strong> Lu, écrit et parlé (langue maternelle)</li>
				<li> <strong>Anglais : </strong> Lu, écrit et parlé (TOEIC 780) </li>
				<li> <strong>Espagnol :</strong>  Lu, écrit et parlé </li>
				<li> <strong>Japonais : </strong> notions (Bac option Japonais)</li>
			</ul>
			<div class="interets"> 
			<h2>Centres d'intérêts</h2>
			<i class="material-icons" style ="font-size: 4em ">local_dining</i>
			<i class="material-icons" style ="font-size: 4em ">party_mode</i>
			<i class="material-icons" style ="font-size: 4em ">local_airport</i>
			<i class="material-icons" style ="font-size: 4em ">directions_bike</i>
			<i class="material-icons" style ="font-size: 4em ">directions_run</i>
			</div>
		</div>

	</div>	
	
	<div class="second_block">
	<h2> Formations et Certifications </h2>
		<h3>Certifications</h3>
				<ul>	
					<li> OPENCLASSROOM : HTML5/ CSS3/JavaScript/Wordpress </li>  
					<li> GOOGLE : Google AdWords / Google Analytics (En cours)</li>
				</ul>
		<h3> Formation</h3>
				<ul>				
					<li> 2017: Intégrateur, développeur WEB , 3W Academy , Paris(RCNP III)</li>
					<li> 2010–2013 : École Supérieure de Commerce, Groupe Sup de Co Amiens (Master II)</li>
					<li> 2007 – 2009:Classe Préparatoire aux grandes Écoles de Commerce (Lycée Charles de Gaulle)</li>
					<li> 2007 : Baccalauréat Sciences Économiques et Sociales (Lycée Charles de Gaulle)</li>
	 			</ul>
		<h2> Expériences Professionnelles</h2>
			<h4> 2014-2017 Chargée de clientèle privée (Société Générale, Versailles)</h4>
				<ul>
					<li>Gestion d’un portefeuille de clients Haut de gamme avoirs entre 50 et 500ke </li>
					<li>Prospection, conquête de nouveaux clients et développement d’un portefeuille clients </li>
					<li>Prospection commerciale, Proposition produits financiers </li>
					<li>Conseil et analyse de l’environnement économique </li>
				</ul>
			<h4> 2013  Ingénieur financier (Cortal Consors, Rueil Malmaison)  </h4>
				<ul>
					<li>Gestion d’un portefeuille de clients Haut de gamme  minimum 50ke</li>
					<li>Passage d’ordres de bourse</li>
					<li>Proposition de différentes gammes d’assurances vie et autres produits financiers</li>
				</ul>
			<h4> 2011-2013: Conseiller clientèle particuliers et professionnels (LCL, Amiens) </h4>
				<ul> 
					<li>  Commercialisation de services afin de répondre aux besoins de 
					la clientèle </li>
					<li> Analyse de la performance, de la gestion et de la stratégie des entreprises </li>
					<li> Évaluation des atouts et contraintes des marchés sur lesquels elles sont positionnées </li>
				</ul>	
					
	</div>	
	</div>	
	</main>




