



<div class="page" > 

<h1>VANESSA CARAES </h1>

<h5> Intégrateur, Développeur WEB </h5>

<ul class="listeaccueil"> 
		<li> <a href="contact.php">Ecrivez-moi </a> </li>
		<li>  <a href="cv.php"> Consulter mon CV </a> </li>
		<li> <a href="https://www.linkedin.com/feed/?trk=" target="_blank"> Consulter mon linkedin</a> </li>
</ul>


<h2> Un bref aperçu de mes réalisations </h2>

	<div class="slideshow">
	<ul>
		<li><img src="../sources/images/slider/1.jpg" alt="" width="550" height="400" /></li>
		<li><img src="../sources/images/slider/2.jpg" alt="" width="550" height="400" /></li>
		<li><img src="../sources/images/slider/3.jpeg" alt="" width="550" height="400" /></li>
		<li><img src="../sources/images/slider/4.jpg" alt="" width="550" height="400" /></li>
	</ul>

	
</div>

<p class="proposition"> Réalisation de sites Vitrines et Dynamiques </p>



</div>




