

<div class="page liens">

<h1> LIENS </h1>


<strong> <p> Parce que vous ne pouvez visiter mon portefolio sans découvrir une partie des blogs et sites qui  m'inspirent </p></strong>

	
	<h2> <a href="https://www.leblogdelamechante.fr/" target="_blank"> Le blog de la Méchante </a>
	</h2>

	<br>

	<img src="../sources/images/liens/eleonore.jpg" width="400px" height="300px">

	<div class="mesliens">
		<p> Quand j'ai envie d'un zeste de folie </p> 
		<p> Quand j'ai besoin d'un peu d'humour </p>
		<p> Quand je cherche des bonnes astuces et des articles intéressants ... </p>
	</div>

	<h2> <a href="https://cuisine-saine.fr/recettes-sans-sucre/faire-bonbons-sains/" target="_blank"> Cuisine Saine </a> </h2>
	<br>

	<img src="../sources/images/liens/cuisine.jpg" width="400px" height="300px"> 
<div class="mesliens">
	<p> Lorsque j'ai envie de manger des choses saines </p>
	<p> Lorsque j'invite des amis ou de la famille </p>
	<p>Lorsque je m'ennuie tout simplement ...</p>
</div>

	<h2> <a href="https://www.alsacreations.com/outils/lire/1747-Audit-20-de-Google-Chrome.html" target="_blank"> AlsaCréation</a> </h2>
	<br>
	<img src="../sources/images/liens/alsacreation.jpg" width="400px" height="300">

	<div class="mesliens">
	<p>Souvent  je travaille tellement que j'en ai des migraines</p>
	<p> Souvent lorsque je ne trouve pas la solution toute seule ... </p>
	</div>

	<h2> <a href="https://openclassrooms.com/dashboard" target="_blank"> OpenClassRoom</a> </h2>
	<br>
	<img src="../sources/images/liens/openclassroom.png" width="400px" height="300px">

	<div class="mesliens">
		<p> Toujours lorsque je veux apprendre un nouveau langage</p>
		<p> Systématiquement quand je veux me certifier dans ce nouveau langage</p> 
	</div>

	<h2> Et tout simplement parce que j'ai découvert  et aimé le développement avec et grâce à  eux </h2>


</div>